# Description:
#   None
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   HWB [n] - Returns the title of hymn # n
#
# Author:
#   davisagli

hymns = [
  "What is this place",
  "In thy holy place we bow",
  "Create my soul anew",
  "Unto thy temple, Lord, we come",
  "There is a place of quiet rest",
  "Here in this place",
  "Here, O Lord, your servants gather",
  "Brethren, we have met to worship",
  "Jesus Lord, how joyful you have made (Jesus A, Nahetotatanome)",
  "Jesus, we want to meet",
  "Sweet hour of prayer",
  "Come, let us all unite to sing",
  "Blessed Jesus, at your word",
  "Come, we that love the Lord",
  "O Prince of peace",
  "God is here among us",
  "We gather together",
  "Before Jehovah's aweful throne",
  "Open now thy gates of beauty",
  "Come and see",
  "All praise to our redeeming Lord",
  "Lord Jesus Christ, be present now",
  "Hear thou our prayer, Lord",
  "Grace to you and peace",
  "Jesus, stand among us",
  "Holy Spirit, come with power",
  "Come, O Creator Spirit",
  "Breathe Upon Us Holy Spirit",
  "Like the murmur of the dove’s song",
  "Spirit divine, inspire our prayers",
  "Wind who makes all winds",
  "Our Father God, thy name we praise",
  "O Gott Vater",
  "When the morning stars together",
  "Many and great, O God",
  "God of our strength",
  "Praise to the Lord, the Almighty",
  "The Lord is in his holy temple",
  "Lord of the worlds above",
  "Jesus Christ, God's only Son",
  "Come, thou Almighty King",
  "All people that on earth do dwell",
  "Christ is our cornerstone",
  "When in our music God is glorified",
  "I cannot dance, O Love",
  "I sing the mighty power of God",
  "Earth and all stars",
  "All creatures of our God and King",
  "From all that dwell below the skies",
  "Praise the Lord, sing hallelujah",
  "Let the whole creation cry",
  "Praise the Lord",
  "God of the earth, the sky, the sea",
  "Praise the Lord who reigns above",
  "Cantemos al Señor (Let's sing unto the Lord)",
  "Awake, arise, O sing a new song",
  "Come and give thanks to the Giver",
  "This is the day",
  "Sing praise to God who reigns",
  "Songs of praise the angels sang",
  "Let all creation bless the Lord",
  "Who is so great a God",
  "Praise, my soul, the God of heaven!",
  "Asithi: Amen (Sing amen)",
  "Praise, my soul, the King of heaven!",
  "O worship the King",
  "Sing hallelujah, praise the Lord",
  "O come, loud anthems let us sing",
  "The Lord is king",
  "Immortal, invisible, God only wise",
  "Joyful, joyful, we adore Thee",
  "When all thy mercies, O my God",
  "Make music to the Lord most high",
  "We would extol thee",
  "Heilig, heilig, heilig (Holy, holy, holy)",
  "Praise, I will praise you, Lord (Je lourai l'Eternal)",
  "God of many names",
  "Ehane he'ama (Father God, you are holy)",
  "Lord, with devotion we pray",
  "O bless the Lord, my soul (Vigil)",
  "Oh, for a thousand tongues to sing (Lyngham)",
  "Great God, how infinite art thou",
  "With happy voices singing",
  "Oh that I had a thousand voices" ,
  "Now thank we all our God" ,
  "Now thank we all our God",
  "Great is the Lord",
  "Still, I search for my God",
  "For the beauty of the earth",
  "For the fruit of all creation",
  "Praise to God, immortal praise",
  "Lord, should rising whirlwinds",
  "Lord, bless the hands",
  "Come, ye thankful people",
  "Praise God, the Source of life",
  "We plow the fields and scatter",
  "From the hands",
  "Sing to the Lord of harvest",
  "We praise thee, O God",
  "Praise him, praise him!",
  "Alleluia",
  "To God be the glory",
  "Jubilate Deo omnis terra",
  "Of the Father's love begotten",
  "Christ, we do all adore thee",
  "All hail the power of Jesus’ name (Coronation)",
  "Blessed Savior, we adore thee",
  "Blessing and honor and glory",
  "I will praise the Lord",
  "Oh, for a thousand tongues to sing (Azmon - familiar tune)",
  "O praise the gracious power",
  "O Lord, our Lord, how majestic",
  "O Christe Domine Jesu",
  "In thee is gladness",
  "Jesus, thou mighty Lord",
  "Crown him with many crowns",
  "Fairest Lord Jesus",
  "Praise God from whom (Dedication Anthem - 606)",
  "Praise God from whom (aka 'Doxology')",
  "Holy, holy, holy!",
  "Holy God, we praise thy name",
  "All glory be to God on high",
  "O Holy Spirit, Root of life",
  "O worship the Lord",
  "To God, with the lamb",
  "How wondrous great",
  "Glory be to the Father",
  "Create in me a clean heart",
  "Fire of God, undying Flame",
  "O God of mystery and might",
  "When in the hour of deepest need",
  "Holy Spirit, Storm of love",
  "Out of the depths I cry to you",
  "Babylon streams received our tears",
  "God, whose purpose is to kindle",
  "From the depths of sin",
  "Forgive our sins as we forgive",
  "Let God, who called the worlds" ,
  "Far, far away from my loving father",
  "Open, Lord, my inward ear",
  "The sacrifice you accept, O God",
  "Brothers and sisters of mine",
  "Amazing Grace!",
  "Kyrie eleison" ,
  "There’s a wideness in God’s mercy",
  "O Lamb of God all holy!" ,
  "Oh, how wondrous the grace",
  "By the waters",
  "Great God of wonders" ,
  "Wonderful grace of Jesus",
  "Marvelous grace of our loving Lord",
  "Kyrie",
  "O Christ, the Lamb of God",
  "This is my Father’s world",
  "O God, great womb",
  "All things bright and beautiful",
  "Lord, our Lord, your glorious name",
  "Since over thy footstool",
  "All beautiful the march of days",
  "God created heaven and earth",
  "We give thanks unto you",
  "The God of Abraham praise",
  "Obey my voice",
  "When Israel was in Egypt's land",
  "A mighty fortress is our God",
  "I'll praise my Maker",
  "For God so loved us",
  "Creating God, your fingers trace (Christopher Dock)",
  "I to the hills will lift my eyes" ,
  "The King of love my shepherd is",
  "How lovely is your dwelling",
  "O come, O come, Immanuel",
  "Savior of the nations, come!" ,
  "Bless'd be the God of Israel",
  "O Savior, rend the heavens",
  "Comfort, comfort, O my people",
  "Creator of the stars of night",
  "Come, thou long-expected Jesus",
  "Blessed be the Lord",
  "The angel Gabriel" ,
  "My soul proclaims with wonder",
  "Oh, how shall I receive thee",
  "On Jordan's banks the Baptist's cry",
  "Hark! The glad sound!",
  "Hail to the Lord's anointed",
  "Fling wide the door, unbar the gate!",
  "Let the heavens be glad",
  "Sleepers, wake!",
  "To us a child of hope is born",
  "'Twas in the moon of wintertime",
  "O little town of Bethlehem",
  "On this day earth shall ring",
  "Silent night, holy night",
  "Away in a manger",
  "It came upon a midnight clear",
  "While shepherds watched",
  "Angels we have heard on high",
  "Let our gladness have no end",
  "The first Noel, the angel did say",
  "Where is this stupendous stranger",
  "Hark! the herald angels sing",
  "The virgin Mary had a baby boy",
  "Break forth, O beauteous heav'nly",
  "Gloria",
  "From heav'n above to earth I come",
  "Infant holy, infant lowly",
  "Nino liñdo (Child so lovely)",
  "Love came down at Christmas",
  "Oh, how joyfully",
  "Good Christian friends, rejoice",
  "Lo, how a rose e’er blooming",
  "O come, all ye faithful",
  "Let all together praise our God",
  "Morning star, O cheering sight!",
  "What child is this",
  "Christ, whose glory fills the skies",
  "When Christ's appearing" ,
  "As with gladness men of old",
  "Bright and glorious is the sky",
  "Worship the Lord in the beauty",
  "Hail the bless'd morn" ,
  "How brightly beams the morning",
  "Woman in the night",
  "The kingdom of God" ,
  "The glory of these forty days" ,
  "You are salt for the earth",
  "Two fishermen" ,
  "Our Father who art in heaven" ,
  "Lord, you have come to the lakeshore",
  "Blessed are the persecuted",
  "Oh, blessed are the poor in spirit" ,
  "Christ upon the mountain peak",
  "Joyful is the dark" ,
  "When Jesus wept, the falling tear" ,
  "My song is love unknown" ,
  "Oh love, how deep, how broad",
  "All glory, laud, and honor",
  "Hosanna, loud hosanna",
  "Ride on, ride on in majesty",
  "Go to dark Gethsemane",
  "Tis midnight, and on Olive’s brow",
  "Stay with me" ,
  "Before the cock crew twice",
  "Alone thou goest forth",
  "At the cross, her vigil keeping" ,
  "Why has God forsaken me?" ,
  "Jesus, remember me",
  "My God, my God, why",
  "Calvary",
  "Beneath the cross of Jesus",
  "How shallow former shadows" ,
  "O sacred Head, now wounded",
  "Alas! And did my Savior bleed?",
  "Ah, holy Jesus" ,
  "Open are the gifts of God" ,
  "Sing, my tongue, the song" ,
  "Were you there",
  "Man of sorrows",
  "When I survey the wondrous cross (Hamburg)",
  "When I survey the wondrous cross (African)",
  "I will sing the Lord's high triumph",
  "At the Lamb's high feast" ,
  "The strife is o'er",
  "Come, ye faithful, raise the strain (St. Kevin)",
  "Come, ye faithful, raise the strain (Ave Virgo Virginium)",
  "They crucified my Savior",
  "Christ has arisen",
  "See the splendor of the morning",
  "Thine is the glory",
  "Who are these",
  "Christ is arisen" ,
  "Christ is risen! Shout hosanna" ,
  "Low in the grave he lay",
  "O sons and daughters, let us sing!",
  "Lift your glad voices" ,
  "This joyful Eastertide" ,
  "I know that my Redeemer lives (Shout on)",
  "Christ is alive! Let Christians sing!",
  "I know that my Redeemer lives (Truro)",
  "Christ the Lord is risen today",
  "That Easter day with joy was bright",
  "Proclaim the tidings near and far",
  "Christ who left his home in glory",
  "Come away to the skies",
  "All hail the power of Jesus’ name (Diadem)",
  "Look, you saints" ,
  "Sing we triumphant hymns" ,
  "Rejoice, the Lord is king!",
  "Filled with the Spirit's power",
  "Spirit, come, dispel our sadness" ,
  "O Holy Spirit, by whose breath",
  "Away with our fears",
  "God sends us the Spirit",
  "Dona nobis pacem Domine",
  "Christ is coming! Let creation",
  "Here from all nations" ,
  "Jesus came - the heavens adoring",
  "Veni Sancte Spiritus",
  "New earth, heavens new",
  "O Holy Spirit, making whole",
  "Joys are flowing like a river",
  "Come, divine Interpreter" ,
  "Come, gracious Spirit" ,
  "There are many gifts",
  "Where charity and love prevail",
  "In Christ there is no East or West",
  "Will you let me be your servant",
  "I love thy kingdom, Lord" ,
  "Built on the rock" ,
  "How good a thing it is" ,
  "The church's one foundation",
  "Lamp of our feet",
  "Rejoice, rejoice in God" ,
  "The word of God is solid ground" ,
  "This is a story full of love" ,
  "In this world abound scrolls",
  "Lord, I have made thy word",
  "Joy to the world",
  "Jesus shall reign",
  "Oh, holy city seen of John" ,
  "Lift high the cross",
  "For we are strangers no more",
  "Beyond a dying sun",
  "Seek ye first the kingdom of God",
  "Creating God, your fingers trace",
  "O Love of God" ,
  "Great is thy faithfulness",
  "O God, our help in ages past",
  "A mighty fortress is our God (rhythmic version)",
  "I believe in God",
  "If Christ is mine" ,
  "Blessed assurance",
  "Christ, who is in the form of God",
  "Christ is the world's true light" ,
  "This is the threefold truth",
  "When peace, like a river",
  "Ask ye what great thing I know" ,
  "I know not why God’s wondrous",
  "Thou art the way",
  "Tis so sweet to trust in Jesus",
  "Jesus loves me",
  "At the name of Jesus",
  "My hope is built on nothing less",
  "I will sing of my Redeemer",
  "God sent his Son",
  "Dona nobis pacem",
  "Through our fragmentary prayers",
  "O Lord, hear my prayer",
  "Spirit of the living God",
  "Lord, teach us how to pray aright",
  "Our Father who art in heaven",
  "Gentle Shepherd, come and lead us",
  "Lord, listen to your children",
  "Fount of love, our Savior God",
  "Savior, like a shepherd lead us",
  "Breathe on me, breath of God",
  "O Master, let me walk with thee",
  "Oyenos, mi Dios",
  "Lead us, O Father",
  "Break thou the bread of life",
  "O Spirit of the living God",
  "Help us to help each other",
  "Renew your church",
  "Spirit of God, unleashed on earth" ,
  "Christ, from whom all blessings" ,
  "God of Grace and God of Glory",
  "For the healing of the nations",
  "O God of love, O Power of peace",
  "Lord, whose love in humble service",
  "O day of God, draw nigh",
  " Let there be light, Lord God",
  "O healing river" ,
  "Thou true Vine, that heals",
  "O young and fearless prophet",
  "Heal us, Immanuel, here we are",
  "O God, thou faithful God",
  "Healer of our every ill",
  "By Peter's house",
  "O Christ, the healer",
  "Let us pray",
  "Amen",
  "Amen",
  "God, whose giving",
  "We give thee but thine own",
  "What gift can we bring",
  "As saints of old" ,
  "Lord, thou dost love",
  "Grant us, Lord, the grace",
  "Take My Life",
  "God of the fertile fields",
  "God, whose farm is all creation",
  "Heart and mind, possessions, Lord",
  "A charge to keep I have",
  "How buoyant and bold the stride",
  "Here I am, Lord",
  "The work is thine, O Christ",
  "God loves all his many people",
  "I love to tell the story",
  "Now go forward",
  "Santo, santo, santo",
  "This little light of mine",
  "Christian, let your burning light",
  "The church of Christ in every age",
  "O Jesus Christ, may grateful hymns",
  "Where cross the crowded ways",
  "And is the gospel peace and love" ,
  "We are people of God’s peace" ,
  "O day of peace",
  "What does the Lord require",
  "Lord of light, your name outshining",
  "I bind my heart this tide",
  "We shall walk through the valley",
  "Faith of the martyrs",
  "God, who stretched",
  "Forth in thy name",
  "For Christ and the church",
  "All who love and serve your city",
  "Move in Our Midst",
  "Lead on, O cloud of Presence",
  "Heart with loving heart united",
  "Bless'd be the tie that binds",
  "May God grant you a blessing (Bwana awabariki)",
  "May the grace of Christ our Savior",
  "God, be merciful and gracious" ,
  "Come, come ye saints",
  "Abide, O dearest Jesus" ,
  "You shall go out with joy",
  "Lord, let us now depart in peace",
  "Go now in peace",
  "God be with you",
  "God be with you",
  "With all my heart I offer" ,
  "Go, my children",
  "Thuma mina",
  "May the Lord, mighty God",
  "All who believe and are baptized",
  "Count well the cost",
  "I sing with exultation",
  "I want Jesus to walk with me",
  "I believe in you, Lord Jesus",
  "I bind unto myself today",
  "Christ be with me",
  "We know that Christ is raised" ,
  "Lord, I want to be a Christian",
  "Come, Holy Spirit, Dove Divine" ,
  "Wade in the water",
  "O Jesus, I have promised",
  "Awake, awake, fling off the night",
  "Jesus took a towel",
  "Here in our upper room",
  "How pleasant is it",
  "Ubi caritas et amor",
  "Let us break bread together",
  "Seed, scattered and sown",
  "Bread of life",
  "Shepherd of souls, refresh",
  "Be present at our table, Lord",
  "Great God, the giver of all good",
  "I come with joy to meet my Lord",
  "Una espiga",
  "In the quiet consecration",
  "Now the silence",
  "Let all mortal flesh keep silence" ,
  "Let the hungry come to me",
  "Here, O my Lord, I see thee",
  "Jesus, sun and shield art thou",
  "Author of life divine",
  "O Bread of life, for sinners broken",
  "Bread of the world",
  "Christ Jesus lay",
  "Eat this bread",
  "I am the Bread of life",
  "Soul, adorn thyself with gladness",
  "I hunger and I thirst",
  "Become to us the living bread",
  "This is the feast",
  "For the bread" ,
  "Sent forth by God’s blessing",
  "Lord of our growing years",
  "Shepherd of tender youth",
  "O God, your constant care",
  "Mothering God, you gave me birth",
  "O God, who gives us life",
  "From time beyond my memory",
  "Teach me the measure of my days",
  "God of our Life",
  "Teach me, O Lord",
  "Strong Son of God, immortal Love",
  "O little children, gather" ,
  "Lord of the home",
  "Softly and tenderly Jesus is calling",
  "God of Eve and God of Mary" ,
  "I heard the voice of Jesus say",
  "Christian, do you hear the Lord?",
  "O let all who thirst",
  "Like Noah's weary dove",
  "Come, ye disconsolate" ,
  "He comes to us as one unknown",
  "Lord, speak to me",
  "As the hart with eager yearning",
  "Come down, O Love divine",
  "Spirit of God! descend",
  "Come, O thou Traveler unknown" ,
  "Have thine own way",
  "I am thine, O Lord",
  "I sought the Lord",
  "Gracious Spirit, dwell with me",
  "Holy Spirit, Truth divine",
  "The tree of life",
  "O Christ, in thee my soul",
  "God, who touches earth",
  "If all you want, Lord",
  "To go to heaven",
  "Lord, I am fondly, earnestly",
  "Jesus, Rock of ages" ,
  "Just as I am, without one plea",
  "Open my eyes, that I may see",
  "Eternal Light, shine in my heart",
  "Shepherd me, O God",
  "Oh, for a closer walk with God",
  "Come, thou fount",
  "My Jesus, I love thee",
  "Dear Lord and Father of mankind",
  "What mercy and divine compassion",
  "How blessed are they",
  "In the rifted Rock I'm resting",
  "Lord Jesus, think on me" ,
  "I stand amazed in the presence",
  "Father, I stretch my hands to thee" ,
  "What wondrous love is this",
  "Ah, what shame I have to bear",
  "I am leaning on the Lord",
  "Jesus, my Lord, my God, my all",
  "Prince of peace, control my will",
  "Who now would follow Christ",
  "Take up your cross",
  "You are the God within life (En medio de la vida)",
  "Lead me, Lord",
  "Make me a captive, Lord",
  "Strong, righteous man of Galilee",
  "How clear is our vocation, Lord",
  "Holy Spirit, gracious Guest",
  "I long for your commandments" ,
  "When we walk with the Lord",
  "Be thou my vision",
  "Guide my feet",
  "My dear Redeemer and my Lord",
  "Teach me thy truth",
  "Savior of my soul",
  "Living and dying with Jesus",
  "In the stillness of the evening",
  "By gracious powers",
  "I am weak and I need thy strength",
  "Our Father, who art in heaven",
  "I need thee every hour",
  "Lord, thou hast searched me" ,
  "O God, in restless living",
  "When the storms of life are raging",
  "O thou, in whose presence",
  "In lonely mountain ways" ,
  "Give to the winds thy fears",
  "Nada te turbe",
  "I to the hills will lift mine eyes",
  "I am trusting thee, Lord Jesus" ,
  "My faith looks up to thee",
  "In the cross of Christ I glory",
  "How firm a foundation",
  "As spring the winter doth succeed",
  "Day by day, dear Lord",
  "We walk by faith",
  "‘Tis not with eyes of flesh we see",
  "Prayer is the soul's sincere desire",
  "What a friend we have in Jesus (Blaenwern)",
  "What a friend we have in Jesus (Erie / Converse)",
  "Precious Lord, take my hand",
  "If you but trust in God",
  "O Love that will not let me go",
  "The Lord's my shepherd",
  "Lift every voice and sing",
  "My life flows on",
  "Take thou my hand, O Father",
  "Guide me, O thou great Jehovah",
  "Ndikhokele, O Jehova",
  "They that wait upon the Lord",
  "In your sickness",
  "Cast thy burden upon the Lord",
  "Come, my Way, my Truth, my Life",
  "Jesus, the very thought of thee",
  "My Shepherd will supply my need",
  "The care the eagle gives her young" ,
  "Lo, a gleam from yonder heaven",
  "Love divine, all loves excelling",
  "O Power of love",
  "Lord, you sometimes speak",
  "Jesus, priceless treasure",
  "And I will raise you up",
  "Oh, how happy are they",
  "A wonderful Savior is Jesus" ,
  "He leadeth me",
  "O bless the Lord, my soul (St. Thomas)",
  "Take my hand and lead me, Father (with refrain)",
  "Take my hand and lead me, Father (without refrain)",
  "Lift up your hearts",
  "Sometimes a light surprises" ,
  "Jesu, Joy of Man's Desiring",
  "I love thee, Lord",
  "Oh, have you not heard",
  "Today I live",
  "If death my friend and me divide",
  "Awake my soul",
  "On Jordan's stormy banks I stand" ,
  "Soon and very soon",
  "Steal away",
  "In heavenly love abiding" ,
  "In the bulb there is a flower",
  "Shall we gather at the river",
  "Children of the heavenly Father",
  "Jesus, keep me near the cross",
  "Jesus, lover of my soul",
  "Glorious things of thee are spoken",
  "Child of blessing, child of promise",
  "Jesus, friend so kind and gentle",
  "Wonder of wonders",
  "When love is found" ,
  "O perfect Love",
  "Your love, O God, has called us",
  "Hear us now, O God our maker",
  "There is a balm in Gilead",
  "At evening, when the sun had set",
  "Immortal Love, forever full",
  "Silence! frenzied, unclean spirit" ,
  "Anoint us, Lord",
  "God the Spirit, Guide and Guardian",
  "Whom shall I send?",
  "Let hope and sorrow now unite",
  "O Lord of life, wherever they be" ,
  "For all the saints",
  "When grief is raw",
  "God is working his purpose out",
  "Great God, we sing",
  "This is a day of new beginnings",
  "O day of rest and gladness",
  "This is the day the Lord has made",
  "Amen (Proulx)",
  "When morning gilds the skies",
  "Each morning brings us",
  "O Splendor of God's glory bright",
  "At break of day (Por la mañana)",
  "Morning has broken",
  "On the radiant threshold",
  "Father, we praise thee",
  "I owe the Lord a morning song",
  "The day you gave us, Lord",
  "Abide with me",
  "Sun of my soul",
  "Now, on land and sea descending",
  "Savior, again to your dear name",
  "Now all the woods are sleeping",
  "All praise to thee, my God",
]

module.exports = (robot) ->
  robot.hear /.*(HWB|hymn)\s*#?\s*(\d+).*/i, (msg) ->
    hymn = parseInt(msg.match[1]);
    msg.send "HWB #" + hymn + ': ' + hymns[hymn - 1]
